FROM node:lts-alpine

USER node

ENV HOME=/home/node PATH=/home/node/.local/bin:$PATH

WORKDIR $HOME/app

ADD . $HOME/app
COPY --chown=node . $HOME/app

RUN npm install

EXPOSE 7860

ENTRYPOINT ["nodejs", "./index.js"]
