FROM node:18

WORKDIR /app

# install pnpm
RUN npm install -g pnpm

# copy manifest
COPY package.json pnpm-lock.yaml ./

# install deps
RUN pnpm install --frozen-lockfile

# copy source
COPY . .

# build TS -> JS
RUN pnpm run build

EXPOSE 7860

CMD ["pnpm", "start"]
