FROM node:18

WORKDIR /app

# INSTALL PNPM (WAJIB)
RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .
RUN pnpm run build

EXPOSE 7860

CMD ["pnpm", "start"]
